feature: add-controllers
B10nicle/java-shareit pull request #1
Opened 2023-01-24 11:06 UTC by B10nicle

2023-01-25 10:10 UTC, ErkinKasymaliev requested changes
Привет, отличная работа!
Оставил комменты, но они в рекомендательные. Оставил их пакет Item, но они также относятся и к User

2023-01-25 10:10 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private final String name;
а почему бы сюда валидацию не поставить? Аннотации имею виду

2023-01-25 10:10 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ItemMapper.toItemDto(itemService.create(ItemMapper.toItem(itemDto), userId));
хмм, а может все маппинги уберем в сервисы? а в контроллер уже будет возвращать dto.

2023-01-25 10:10 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
я бы сделал единый интерфейс для маппера, например BaseMapper.
public interface BaseMapper <M, D> {
    M toModel(D d);
    D toDto(M m);
}
потом будем создавать мапперы для всех сущностей и имплементить этот интерфейс, который и будем инжектить.

2023-01-28 10:03 UTC, B10nicle commented
Эркин, привет! Ответил по тексту

2023-01-28 10:05 UTC, B10nicle commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private final String name;
Это как и в прошлом проекте - аннотации ломают некоторые тесты, сейчас снова попробовал - добавил @NotBlank и @Email на Dto + @Valid в контроллере, у меня падают 5 тестов. Мне проще написать валидацию, которая 100% проходит тесты чем танцевать с бубном вокруг тестов.

2023-01-28 10:07 UTC, B10nicle commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ItemMapper.toItemDto(itemService.create(ItemMapper.toItem(itemDto), userId));
Тоже попробовал + попробовал перейти на мапстракт - ломается проект, попробую сделать когда будет репозиторий

2023-01-28 10:16 UTC, B10nicle commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
Проблема данной реализации в том что ты закрываешься на двух сущностях, если будет необходимость подкрутить любую из них чем-то из вне, то будет необходимо писать новый интерфейс\реализацию (покрываем не все кейсы) и так как непонятно что будет дальше по проекту, то я бы предпочел оставить пока что в текущем виде.

Вот примеры с чем сталкивался:
![image](https://user-images.githubusercontent.com/92729800/215260848-28848da8-4457-45b3-8c2f-61cbe22ec614.png)
![image](https://user-images.githubusercontent.com/92729800/215260883-49cf87c3-4006-465f-a3c6-cdb20c65c604.png)
![image](https://user-images.githubusercontent.com/92729800/215261011-98238567-af33-4954-92b5-6355451a664a.png)

2023-01-28 14:26 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-01-29 04:36 UTC, B10nicle commented
Эркин, спасибо за ревью!

2023-01-29 04:36 UTC, merged