feature: add-item-requests
B10nicle/java-shareit pull request #3
Opened 2023-02-12 21:33 UTC by B10nicle

2023-02-12 21:36 UTC, B10nicle commented
Эркин, привет! Высылаю работу на ревью

2023-02-13 18:47 UTC, ErkinKasymaliev requested changes
привет, как обычно все четко)
оставил пару комментов

2023-02-13 18:47 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.save(itemDto, itemRequestDto, userId);
если itemRequestDto станет null, то ты сохранишь null?

2023-02-13 18:47 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceUnitTest.java
> +        assertEquals(allItemRequests.size(), 1);
еще бы неплохо было добавить проверки типа
verify(someRepository, times(3))
        .findById(any(Long.class)); - то есть ты проверяешь что сервис дергает репозиторий нужное кол-во раз
эту проверку можно поставить в методах сервисов, где есть вызов нескольких репозиториев или вызов БД.
Коммент рекомендательный

2023-02-13 20:30 UTC, B10nicle commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.save(itemDto, itemRequestDto, userId);
да, так как так и должно быть, потому что itemRequestDto не является обязательным параметром и если его нет в запросе, то я маплю Item в ItemServiceImpl и сохраняю в бд, то есть проверка на то что данное поле null и не сохранение в БД не отвечает условиям текущей задачи. Если бы было иначе, то у меня падали бы тесты на сохранение в бд, где данное поле null, а они (тесты) не должны зависеть от логики данного поля.

2023-02-13 20:34 UTC, B10nicle commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceUnitTest.java
> +        assertEquals(allItemRequests.size(), 1);
Хорошо, приму к сведению, спасибо, так еще не проверял, попробую реализовать на дипломе

2023-02-14 13:32 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-02-14 14:00 UTC, B10nicle commented
Привет, спасибо за ревью!

2023-02-14 14:00 UTC, merged